2020/01/31
DeepSpeech training 도중 아래와 같은 cudnn error 발생
Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above
인터넷을 찾아본 결과 cuda/cudnn과 텐서플로우 등의 호환성 문제로 보이며 아직 cudnn이나 텐서플로우 등이 완벽하게 호환되지 않는 듯 하다. 
되다가 안된다는 경우가 꽤 있음.
ternsorflow gpu version을 1.15에서 1.14로 downgrade후에 잘 동작한다. 1.15는 계속 안된다.
이유를 알수는 없지만 호환성이 깨진듯

위 이슈 관련 시도해 보았던 것
1. 코드 리뷰 - 의외로 사소한 실수일 수 있다.
2. nvidia gpu driver 재설치(clean 후 reinstall)
3. cuda, cudnn 재설치
4. tensorflow를 비롯한 python 가상환경 재설치
5. 전역 pip list 삭제..
6. tensorflow downgrade to 1.14 후 비로소 training 정상 동작.


2020/02/03
1/31 cudnn issue관련 training은 잘 되었지만 inference시에 ctc_decoder를 불러오는 부분에서 segmentation error 발생, 
ctc decoder는 c++로 개발된 모듈을 binary형태로 파이썬에서 불러오는 형태로 현재 디버깅을 하기가 쉽지 않아 포맷 진행
format 후에 pip3 -r requirement.txt 중 아래와 같은 error 발생, 
building '_webrtcvad' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/cbits
  creating build/temp.linux-x86_64-3.6/cbits/webrtc
  creating build/temp.linux-x86_64-3.6/cbits/webrtc/common_audio
  creating build/temp.linux-x86_64-3.6/cbits/webrtc/common_audio/signal_processing
  creating build/temp.linux-x86_64-3.6/cbits/webrtc/common_audio/vad
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWEBRTC_POSIX -Icbits -I/usr/include/python3.6m -I/home/beomgon2/deepspeech-train-venv/include/python3.6m -c cbits/pywebrtcvad.c -o build/temp.linux-x86_64-3.6/cbits/pywebrtcvad.o
  cbits/pywebrtcvad.c:1:10: fatal error: Python.h: No such file or directory
   #include <Python.h>
            ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
git lfs 설치 중 apt package관련 설정등이 바뀐 것으로 보이며 apt-update 이후에 정상설치

텐서플로우 관련 한글번역 문서 study 중


0205
1. 딥러닝 교육 관련 소제목 및 내용 간략히 정리
2. 2/3일에서 zeroth data기준 csv file format으로 변환, but 이후 training시 아래 에러 재발생
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
     [[{{node tower_0/conv1d/Conv2D}}]]
     v0.7.0-alpha.1 버전에서 tensorflow-gpu version 1.14로 해도 여전히 발생, 
     git latest code base로 변환, git 설치 문서 확인 중 TF_FORCE_GPU_ALLOW_GROWTH environment variable to true 로 세팅하라는 부분 확인
     세팅 후 여전히 같은 에러 발생
     tensorflow-gpu version 1.15에서 1.14로 다운그레이드 후 training 성공
     
     Latest branch가 아닌 release branch로 받아서 테스트해야 두 PC의 환경이 완전히 똑같다. 
     
 3. kenlm에서 MAX order가 6이고 7 이상으로 설정시 cmake를 이용해 빌드를 다시 해야 한다. 
     cmake -DKENLM_MAX_ORDER=10 ..
    파이썬 연동치 ds_decoder init할때 ngram order가 6을 초과해서 error 발생,
    6으로 바꾼 후 inferencing 성공
    자모에서 더 세분화할 경우를 테스트하려면 max_order를 10 이상으로 설정할 수 있어야 한다. 
 
     
